name: workflow for Java using Snyk

on: push

permissions:
  issues: write
  contents: read
  pull-requests: write
  packages: read
  repository-projects: write
  security-events: write
  statuses: read

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 22
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/22.0.2-9/x64
      DEBUG: "*"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: adopt

      - name: Verify JAVA_HOME
        run: |
          echo $JAVA_HOME
          java -version
          mvn  -version

      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
          }' \
          --fail
      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Verify Snyk installation
        run: snyk -v
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Run Maven Dependency Check
        run: snyk test --sarif-file-output=snyk.sarif --file=pom.xml

      - name: Run Synk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-22@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif
      - name: List directory contents
        run: ls -al
      - name: Capture Snyk output
        run: cat snyk.sarif || echo "SARIF file not found or cannot be read."

      - name: Upload result to GIthub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
